# Generated by cpp11: do not edit by hand

get_sheet_names_ <- function(file, include_external_data) {
  .Call(`_readODS_get_sheet_names_`, file, include_external_data)
}

get_flat_sheet_names_ <- function(file, include_external_data) {
  .Call(`_readODS_get_flat_sheet_names_`, file, include_external_data)
}

read_flat_ods_ <- function(file, start_row, stop_row, start_col, stop_col, sheet_index, formula_as_formula) {
  .Call(`_readODS_read_flat_ods_`, file, start_row, stop_row, start_col, stop_col, sheet_index, formula_as_formula)
}

read_ods_ <- function(file, start_row, stop_row, start_col, stop_col, sheet_index, formula_as_formula) {
  .Call(`_readODS_read_ods_`, file, start_row, stop_row, start_col, stop_col, sheet_index, formula_as_formula)
}

splice_sheet_ <- function(original_xml, sheet_file, flat) {
  .Call(`_readODS_splice_sheet_`, original_xml, sheet_file, flat)
}

update_sheet_ <- function(original_xml, sheet_file, flat, sheet_index) {
  .Call(`_readODS_update_sheet_`, original_xml, sheet_file, flat, sheet_index)
}

write_sheet_file_ <- function(filename, x, sheet_name, row_names, col_names, na_as_string, padding, header, footer) {
  .Call(`_readODS_write_sheet_file_`, filename, x, sheet_name, row_names, col_names, na_as_string, padding, header, footer)
}

write_sheet_file_list_ <- function(filename, x, sheet_name, row_names, col_names, na_as_string, padding, header, footer) {
  .Call(`_readODS_write_sheet_file_list_`, filename, x, sheet_name, row_names, col_names, na_as_string, padding, header, footer)
}
