# Generated by cpp11: do not edit by hand

get_sheet_names_ <- function(file, include_external_data) {
  .Call(`_readODS_get_sheet_names_`, file, include_external_data)
}

get_flat_sheet_names_ <- function(file, include_external_data) {
  .Call(`_readODS_get_flat_sheet_names_`, file, include_external_data)
}

read_flat_ods_ <- function(file, start_row, stop_row, start_col, stop_col, sheet, formula_as_formula) {
  .Call(`_readODS_read_flat_ods_`, file, start_row, stop_row, start_col, stop_col, sheet, formula_as_formula)
}

read_ods_ <- function(file, start_row, stop_row, start_col, stop_col, sheet, formula_as_formula) {
  .Call(`_readODS_read_ods_`, file, start_row, stop_row, start_col, stop_col, sheet, formula_as_formula)
}

write_sheet_ <- function(filename, x, sheet, row_names, col_names, na_as_string, padding, header, footer) {
  .Call(`_readODS_write_sheet_`, filename, x, sheet, row_names, col_names, na_as_string, padding, header, footer)
}
