# TODO allow list of df...
# so that df=smartSheet(read.ods("test.ods")) can become a thing!




#' smartSheet
#' 
#' @description
#' needs a better name!
#' checks if a sheet generated by readODS has col or row names and updates them
#' 
#' @param df the data.frame to be changed
#' @param trim should empty rows and column be removed?
#' @param colNames "smart" TRUE or FALSE
#' 
#' @export
smartSheet=function(df=NULL, trim=TRUE, colNames="smart", rowNames="smart"){
  idf=df
  print("smartSheet")
#   print(idf)
  # remove empty rows and columns
  if(trim){
    #check rows
    noneEmptyRows=NULL
    for(i in 1:dim(idf)[1]){
      if(any(idf[i,]!="")){
        noneEmptyRows=append(noneEmptyRows,i)
      }
    }
    idf=idf[noneEmptyRows,]
  
    #check cols
    noneEmptyCols=NULL
    for(i in 1:dim(idf)[2]){
      if(any(idf[,i]!="")){
        noneEmptyCols=append(noneEmptyCols,i)
      }
    }
    idf=idf[,noneEmptyCols] 
  }
#   print("after trim:")
#   print(idf)
  
  if(rowNames=="smart"){
    # check for rowNames
    if(idf[1,1]=="" && idf[2,1]!=""){
#       print(rownames(idf))
#       print(idf[2:dim(idf)[1],1])
      
#       rownames(idf)=idf[2:dim(idf)[1],1]
      rownames(idf)=idf[,1]
      idf=idf[,2:dim(idf)[2]]
    }
  }else if(rowNames){
    # force row names
    # TODO FIX!! if no header or...
    rownames(idf)=idf[,1]
    idf=idf[2:dim(idf)[1],]
  }else{
    # false
  }

  print("after row names:")
  print(idf)
  
  # check colNames
  if(colNames=="smart"){#default
    # check for header
    
    # note that rownames are already removed at this point
    nrOfRows=dim(idf)[1]
    nrOfCols=dim(idf)[2]
    header=F
    for(i in 1:nrOfCols){
      if(tryCatch(as.double(idf[,i]),warning=function(e)T)!=
         tryCatch(as.double(idf[2:nrOfRows,i]),warning=function(e)T) ){
        header=T
      }
    }
    
    
  }else if(colNames){
    # force colname
    colnames(idf)=idf[1,]
    idf=idf[2:dim(idf)[2],]
  }else{
    # false
  }

  print("after col names:")
  print(idf)

  # convert columns to doubles and stuff...

  return(idf)
}

#' givesWarning
#' 
#' @param x the thing you wanna test
#' 
#' @description
#' returns true if a warning was given
#' returns false if no warning was given
#' 
#' 
#' @export
givesWarning=function(x){
  givesWarning=F
  tryCatch(x,warning=function(e){
    givesWarning=T
    print("WTF!")
    return(T)
  })
  return(givesWarning)
}


