## # TODO allow list of df...
## # so that df=smartSheet(read.ods("test.ods")) can become a thing!




## #' smartSheet
## #' 
## #' @description
## #' needs a better name!
## #' checks if a sheet generated by readODS has col or row names and updates them
## #' 
## #' use it as: df=smartSheet(read.ods("test.ods"))
## #' 
## #' @param df the data.frame to be changed
## #' @param trim should empty rows and column be removed?
## #' @param colNames "smart" TRUE or FALSE
## #' @param rowNames "smart" TRUE or FALSE
## #' @param removeEmptySheets removes sheets from the list if they contain no values
## #' @param convertToNumbers converts number columns to doubles
## #' 
## #' 
## #' 
## #' @export
## # Note: data.frames are horrible, they remove row and colnames at random...
## smartSheet=function(df=NULL, trim=TRUE, colNames="smart", rowNames="smart", removeEmptySheets=TRUE, convertToNumbers=TRUE){
##   wasDf=F
##   if(class(df)=="data.frame"){
##     df=list(df)
##     wasDf=T
##   }else if(class(df)=="list"){
##     # good! well only if it contains data.frames..
##   }else{
##     stop(paste("this function only accepts data.frame or a list of data.frames as input, and not: ",class(df),sep=""))
##   }
  
##   returnValue=NULL
##   removedSheets=0

  
##   for(i in 1:length(df)){
##     idf=df[[i]]
    
    
##     colNameValues=NULL
##     rowNameValues=NULL
    
## #     print(idf)
    
##     if(class(idf)!="data.frame"){
##       stop(paste("this function only accepts data.frame or a list of data.frames as input, and not: ",class(df),sep=""))
##     }
    
##     # dont try empty sheets
##     if(all(dim(idf)[1]==c(1,1)) && idf[1,1]==""){
##       print(paste("sheet: ",i," is empty",sep=""))
##       if(removeEmptySheets){
##         removedSheets=removedSheets+1
##         next # skip the rest...
##       }
##     }
    
##     # remove empty rows and columns
##     if(trim){
##       #check rows
##       noneEmptyRows=NULL
      
##       for(j in 1:dim(idf)[1]){
##         if(any(idf[j,]!="")){
##           noneEmptyRows=append(noneEmptyRows,j)
##         }
##       }
##       idf=idf[noneEmptyRows,]
      
##       if(class(idf)=="character"){
##         if(length(idf)==1){
##           print(paste("sheet: ",i," has only 1 cell",sep=""))
##           idf=data.frame(A=idf,stringsAsFactors = F)
##           returnValue[[i-removedSheets]]=idf
##           next
##         }else{
## #           print(paste("sheet: ",i," only has 1 column",sep=""))
##           # will get caught in another catch... so don't double print the message
##           idf=data.frame(A=idf,stringsAsFactors = F)
##         }
##       }
## #       print(idf)
      
##       #check cols
##       noneEmptyCols=NULL
##       for(j in 1:dim(idf)[2]){
##         if(any(idf[,j]!="")){
##           noneEmptyCols=append(noneEmptyCols,j)
##         }
##       }
##       idf=idf[,noneEmptyCols]
      
## #       print(idf)
      
      
##       if(class(idf)=="character"){
##         if(length(idf)==1){
##           print(paste("sheet: ",i," has only 1 cell, and atleast 1 empty column",sep=""))
##           idf=data.frame(A=idf,stringsAsFactors = F)
##           returnValue[[i-removedSheets]]=idf
##           next
##         }else{
##           print(paste("sheet: ",i," has only 1 column",sep=""))
##           idf=data.frame(A=idf,stringsAsFactors = F)
##         }
##       }
##     }
## #     print("after trim:")
## #     print(idf)
    
##     if(dim(idf)[1]==1){
##       print(paste("sheet: ",i," only had 1 row",sep=""))
##       print("i can't handle that shit, well...")
##       returnValue[[i-removedSheets]]=idf
##       next
##     }
    
## #     print(idf)
    
##     if(rowNames=="smart"){
##       # check for rowNames
##       if(idf[1,1]=="" && idf[2,1]!=""){
##         rowNameValues=idf[,1]
##         idf=data.frame(idf[,2:dim(idf)[2]],stringsAsFactors = F)
##       }
##     }else if(rowNames){
##       # force row names
##       # TODO FIX!! if no header or...
##       rowNameValues=idf[,1] 
##       idf=data.frame(idf[,2:dim(idf)[2]],stringsAsFactors = F) #remove rownames column from data, somehow this also removed the row names itself...
##     }else{
##       # false
##     }
    
## #     print("after row names:")
## #     print(idf)
    
##     # check colNames
##     if(colNames=="smart"){#default
##       # check for header
      
##       # note that rownames are already removed at this point
##       nrOfRows=dim(idf)[1]
##       nrOfCols=dim(idf)[2]
##       header=F
##       for(j in 1:nrOfCols){
##         # if you can convert without but not with first line
##         # indicating that first line is a string and rest are numbers
##         # indicating that the first line is a header
##         if(givesWarning(as.double(idf[,j]))!=givesWarning(as.double(idf[2:nrOfRows,j]))){
##           header=T
##         }
##       }
##       if(header){
##         colNameValues=idf[1,]
##         idf=data.frame(idf[2:dim(idf)[1],],stringsAsFactors = F)
##       }
##     }else if(colNames){
##       # force colname
##       colNameValues=idf[1,]
##       idf=data.frame(idf[2:dim(idf)[1],],stringsAsFactors = F)
##     }else{
##       # false
##     }
    
## #     print("after col names:")
## #     print(idf)

##     # convert columns to doubles and stuff...
##     if(convertToNumbers){
##       nrOfCols=dim(idf)[2]
##       for(j in 1:nrOfCols){
## #         print(idf[,j])
## #         print(as.double(idf[,j]))
##         if(!givesWarning(as.double(idf[,j]))){
## #           print(!givesWarning(as.double(idf[,j])))
## #           print(idf[1:5,j])
##           idf[,j]=as.double(idf[,j])
##         }
##       }
##     }


##     # update rownames
##     if(!is.null(rowNameValues)){
##       if(length(rowNameValues)>dim(idf)[1]){
##         # 
##         rownames(idf)=rowNameValues[2:length(rowNameValues)]
##       } else{
##         rownames(idf)=rowNameValues
##       }
      
##     }
##     else{
##       rownames(idf)=1:dim(idf)[1]
##     }
##     # update colnames
##     if(!is.null(colNameValues)){
##       colnames(idf)=colNameValues
##     }
##     else{
##       colnames(idf)=numberToLetters(1:dim(idf)[2])
##     }
##     # return the right thing
##     if(wasDf){
##       returnValue=idf
##     }else{
##       returnValue[[i-removedSheets]]=idf
##     }
##   }#for each sheet
  
##   return(returnValue)
## }

## #' givesWarning
## #' 
## #' @param x the thing you wanna test
## #' 
## #' @description
## #' returns true if a warning was given
## #' returns false if no warning was given
## #' 
## #' 
## #' @export
## givesWarning=function(x){
##   return(tryCatch(expr={x;F},warning=function(w)return(T)))
## }


